name: Test and Coverage
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install build tools
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test
      - name: Run tests with coverage
        run: pnpm test:coverage
