name: Deploy React Vite and Vue Examples and TypeScript to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn
        working-directory: ./examples/vite+react
      - name: Build React App
        run: yarn build
        working-directory: ./examples/vite+react
      - name: Upload React Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: ./examples/vite+react/build

  build-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
        working-directory: ./examples/vue
      - name: Build Vue App
        run: npm run build
        working-directory: ./examples/vue
      - name: Upload Vue Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vue-build
          path: ./examples/vue/build

  build-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
        working-directory: ./examples/typescript
      - name: Build TypeScript App
        run: npm run build
        working-directory: ./examples/typescript
      - name: Upload TypeScript Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: typescript-build
          path: ./examples/typescript/build

  deploy:
    runs-on: ubuntu-latest
    needs: [build-react, build-vue, build-typescript]
    steps:
      - uses: actions/checkout@v3
      - name: Download React Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./public
      - name: Download Vue Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: vue-build
          path: ./public
      - name: Download TypeScript Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: typescript-build
          path: ./public
      - name: Copy index.html to public directory
        run: cp ./examples/index.html ./public/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          allow_empty_commit: true
